apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-ubuntu-slave-deploy
  namespace: jenkins
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-ubuntu-slave
  template:
      metadata:
        labels:
          app: jenkins-ubuntu-slave
      spec:
        containers:
        - name: jenkins-ubuntu-slave
          image: hadilotfy/jenkins-ubuntu-slave:v1   # :v0           
          imagePullPolicy: Never
          ports:
          - containerPort: 22
          volumeMounts:
          - mountPath: /var/run/docker.sock                  # need chmod
            name: docker-sock
        volumes:
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock
